# Generated by Django 4.1.4 on 2022-12-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('inscripcion', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=50)),
                ('estado_de_reserva', models.CharField(choices=[('d', 'Disponible'), ('r', 'Reservado'), ('c', 'Cancelado'), ('a', 'Anulado')], default='d', max_length=1)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.institucion')),
            ],
        ),
    ]
